app/mod/models.py
from enum import unique
from app import db

class TradeDocMaster(db.Model):
    __tablename__ = "trade_doc_master"

    id = db.Column(db.Integer, unique=True, primary_key=True)
    unique_id = db.Column(db.String, unique=True, nullable=False)
    file_name = db.Column(db.String, unique=False, nullable=True)
    port_of_loading = db.Column(db.String, unique=True, nullable=True)
    port_of_discharge = db.Column(db.String, unique=True, nullable=True)
    port_of_receipt = db.Column(db.String, unique=True, nullable=True)
    port_of_delivery = db.Column(db.String, unique=True, nullable=True)
    exporter_name = db.Column(db.String, unique=True, nullable=True)
    exporter_location = db.Column(db.String, unique=True, nullable=True)
    consignee_name = db.Column(db.String, unique=True, nullable=True)
    consignee_location = db.Column(db.String, unique=True, nullable=True)
    notify_name = db.Column(db.String, unique=True, nullable=True)
    notify_location = db.Column(db.String, unique=True, nullable=True)
    buyer_name = db.Column(db.String, unique=True, nullable=True)
    buyer_location = db.Column(db.String, unique=True, nullable=True)
    other_locations = db.Column(db.String, unique=True, nullable=True)
    other_org_names = db.Column(db.String, unique=True, nullable=True)
    product = db.Column(db.String, unique=True, nullable=True)
    person = db.Column(db.String, unique=True, nullable=True)
    vessel = db.Column(db.String, unique=True, nullable=True)
    email = db.Column(db.String, unique=True, nullable=True)

app/mod/views.py
from enum import unique
import os
from uuid import uuid1
from flask import Blueprint, render_template
from jinja2 import TemplateNotFound
from werkzeug.exceptions import abort

from app import db, app, logging
from app.mod.aml_src.process import Process
from app.mod.models import TradeDocMaster

logger = logging.getLogger(__name__)

blueprint_aml = Blueprint("aml", __name__, template_folder="templates", static_folder="static", static_url_path="/static")

@blueprint_aml.route("/", methods=["GET"])
def index():
    try:
        return render_template("index.html")
    except TemplateNotFound:
        return abort(404)

@blueprint_aml.route("/network_files", methods=["GET"])
def network_files():
    try:
        folder_path = os.path.join(os.getcwd(), "shared", "input")
        files = os.listdir(folder_path)
        unique_ids = [str(uuid1().int) for _ in files]

        db.create_all()
        db.session.add_all([TradeDocMaster(unique_id=i, file_name=file) for i, file in zip(unique_ids, files)])
        db.session.commit()

        return render_template("network_files.html", folder_path=folder_path, data=zip(unique_ids, files))
    except TemplateNotFound:
        return abort(404)

@blueprint_aml.route("/show_extraction/<unique_id>", methods=["GET"])
def show_extraction(unique_id):
    try:
        if unique_id:
            result = TradeDocMaster.query.filter_by(unique_id=unique_id).first()
            file_name = result.file_name

            p = Process()
            ocr_results = p.job(unique_id, file_name)

            return render_template("show_extraction.html", unique_id=unique_id)
    except TemplateNotFound:
        return abort(404)

app/mod/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('aml.static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <title>AML Welcome Page</title>
</head>

<body>
    <main>
        <div class="container py-4">
            <header class="pb-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">Mizuho AML System</span>
                </a>
            </header>

            <div class="row align-items-md-stretch">
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>Scan network directory - PDF files</h2>
                        <p>...</p>
                        <a href="{{ url_for('aml.network_files') }}"><button class="btn btn-outline-secondary"
                                type="button">Start Scan</button></a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>List of scanned PDF</h2>
                        <p>...</p>
                        <button class="btn btn-outline-secondary" type="button">Show PDF</button>
                    </div>
                </div>
            </div>

            <footer class="pt-3 mt-4 text-muted border-top">
                Mizuho Bank &copy; 2021
            </footer>
        </div>
    </main>

    <script src="{{url_for('aml.static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>

app/mod/templates/network_files.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('aml.static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <title>AML Welcome Page</title>
</head>

<body>
    <main>
        <div class="container py-4">
            <header class="pb-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">Mizuho AML System</span>
                </a>
            </header>

            <div class="row align-items-md-stretch">
                <div class="col-md-12">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>List of files in shared drive</h2>
                        <b>{{ folder_path }}</b>
                    </div>
                </div>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">ID</th>
                            <th scope="col">PDF Name</th>
                            <th scope="col">File Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if data %}
                        {% for id, file in data %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>
                            <td><a href="{{ url_for('aml.show_extraction', unique_id=id) }}">{{ id }}</a></td>
                            <td>{{ file }}</td>
                            <td>PDF</td>
                        </tr>
                        {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
            </div>

            <footer class="pt-3 mt-4 text-muted border-top">
                Mizuho Bank &copy; 2021
            </footer>
        </div>
    </main>

    <script src="{{url_for('aml.static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>

app/mod/templates/show_extraction.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{url_for('aml.static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
    <title>AML Welcome Page</title>
</head>

<body>
    <main>
        <div class="container py-4">
            <header class="pb-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <span class="fs-4">Mizuho AML System</span>
                </a>
            </header>

            <div class="row align-items-md-stretch">
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>Extracted data from pdf</h2>
                        <p>{{ unique_id }}</p>
                        <form action="#" method="POST">
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">port_of_loading</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">port_of_discharge</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">port_of_receipt</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">port_of_delivery</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">exporter_name</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">exporter_location</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">consignee_name</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">consignee_location</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">notify_name</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">notify_location</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">buyer_name</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">buyer_location</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">other_locations</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">other_org_names</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">product</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">person</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">vessel</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="staticEmail" class="col-sm-4 col-form-label">email</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
                                </div>
                            </div>
                            <p><input type="submit" value="submit" /></p>
                        </form>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>Loaded pdf</h2>
                        <p>...</p>
                    </div>
                </div>
            </div>

            <footer class="pt-3 mt-4 text-muted border-top">
                Mizuho Bank &copy; 2021
            </footer>
        </div>
    </main>

    <script src="{{url_for('aml.static', filename='js/bootstrap.bundle.min.js')}}"></script>
</body>

</html>